services:
  my_database_cont:
    build: ./database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_db
  
  my_backend_cont:
    depends_on:
      - my_database_cont
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ~/Downloads/:/app/data/
    environment:
      - DB_HOST=my_database_cont
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=user_db

  my_frontend_cont:
    depends_on:
      - my_backend_cont
      - my_database_cont
    build: ./frontend
    ports:
      - "5173:5173"

volumes:
  mysql-vol: {}